language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: d7c50549-0e0b-4c87-913b-9831e1b94eff
  app: tekkojuku-cal
  on:
    repo: vcordero07/tekkojuku-cal
